version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
environment:
  Verbosity: Normal
build_script:
- ps: >-
    cd .\build


    $branch="$($env:APPVEYOR_REPO_BRANCH)"

    if($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH -ne "")

    {
        $branch = "$($branch)/$($env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH)"
    }


    .\build.ps1 -Verbosity $env:Verbosity -branch="$($branch)"
test: off