version: 0.1.{build}
build_script:
- ps: >-
    cd .\build


    .\build.ps1 -branch=$env:APPVEYOR_REPO_BRANCH /$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH
deploy:
- provider: NuGet
  api_key:
    secure: /fbpg147kjCtvGcGUu428AtYkI6WAs35Hv3qICOCWLhV9f6ff1vp9nNJ0Fx2Gu57
  skip_symbols: true
  on:
    branch: Release-*